#!/usr/bin/env bash
# Install this repo's git hooks. Run once per clone, and again after changing
# the hook body below:
#
#   scripts/install-hooks.sh
#
# Run this on the box that SERVES the app (the Lenovo), not on a dev clone: the
# hook restarts uvicorn after every pull, which on a dev machine would start a
# server nobody asked for and fight the one you run by hand.
#
# Hooks live in .git/hooks, which git does not version or pull. That is exactly
# how the 2026-07-31 outage happened: deploy-web.sh learned to wait for the
# flock as well as the port, the post-merge hook kept its own older copy of the
# restart logic with a port-only wait, and `git pull` on the box still restarted
# the racy way. Nothing propagated the fix, because nothing could.
#
# So the hook is now a thin wrapper with no restart logic of its own — the fix
# for the class of bug, not just the instance. Keep it that way: if you find
# yourself adding a `kill` or a `uvicorn` line here, put it in deploy-web.sh
# instead. web/tests/test_hooks.py enforces this.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$PWD"
HOOKS_DIR="$(git rev-parse --git-path hooks)"
mkdir -p "$HOOKS_DIR"

cat > "$HOOKS_DIR/post-merge" <<'HOOK'
#!/usr/bin/env bash
# Restart the web app after every pull/merge so pulled code takes effect —
# this uvicorn runs without --reload, so new files on disk change nothing until
# the process is replaced.
#
# GENERATED by scripts/install-hooks.sh. Edit the hook body there, not here.
#
# Delegates to deploy-web.sh so there is exactly one restart implementation.
# --no-pull because git has already merged by the time post-merge runs, and a
# nested git command inside a hook inherits GIT_DIR/GIT_INDEX_FILE from the
# invoking git and would act on the wrong repository.
set -uo pipefail
unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_PREFIX
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
exec "$REPO/scripts/deploy-web.sh" --no-pull
HOOK

chmod +x "$HOOKS_DIR/post-merge"
echo "installed: $HOOKS_DIR/post-merge -> deploy-web.sh --no-pull"
